### ISSUE TITLE
plumbing tests fail on the verifybamid

### ISSUE THREAD

**Issue by leipzig** [broadinstitute/warp#279]
I am seeing the `Required file output '/cromwell_root/NA12878_PLUMBING.preBqsr.selfSM' does not exist.` with the running the WholeGenomeGermlineSingleSample plumbing test set

this seems to be an old issue:
https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/issues/25

https://sites.google.com/a/broadinstitute.org/legacy-gatk-forum-discussions/2020-01-07-2019-07-10/24408-bug-in-gatk-exome-pipeline---verifybamid-step

**Comment by kbergin** [comment]
Hi Jeremy,

Thanks for calling that to our attention. We'll consider updating our plumbing data to better cover the contamination sites in the future, but for now we recommend adding this input to your input json which will cause the pipeline to ignore when there are insufficient markers covered for contamination calculation. 

https://github.com/broadinstitute/warp/blob/3d974069dcf42b37ba7aafc23ada8614ccded76a/pipelines/broad/dna_seq/germline/single_sample/wgs/test_inputs/Plumbing/G96830.NA12878.json#L59

It will still run the contamination tool but it will let the pipeline pass even when contamination couldn't be calculated successfully due to insufficient markers.

We'll update our example input json to match our plumbing test input and include that input, those got out of sync. Or perhaps we will only maintain one plumbing input example, a bit illogical to have two that should be the same.

Thanks!
Kylee
