### ISSUE TITLE
docker images can not pulling

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [broadinstitute/warp#839]
I am installing ExomeGermlineSingleSample pipeline because for some reason I can't access us.gcr.io/broad-gotc-prod . Is there another image I can use directly?
For example, use broadinstitute/genomes-in-the-cloud to replace us.gcr.io/broad-gotc-prod in all wdl files

**Comment by jessicaway** [comment]
Hi @zhaohongqiangsoliva, 
We do not recommend replacing any of the images with the old genomes-in-the-cloud image. Which docker image are you running into permissions issues for? All of the images in this pipeline are intended to be public.

**Comment by zhaohongqiangsoliva** [comment]
Oh I can't access google gcr because of network, but I can access docker hub so I'm looking for an alternative to gcr

**Comment by jessicaway** [comment]
Hi @zhaohongqiangsoliva,

We unfortunately do not have our docker files on Docker Hub. We are currently thinking about alternatives to GCR, but in the meantime, all our docker files and build scripts are available in Warp. For example, here are there the files for the samtools-picard-bwa docker: https://github.com/broadinstitute/warp/tree/develop/dockers/broad/samtools_picard_bwa. You should be able to build the dockers and push them to some place you have access to. 

You can just comment out the lines that push the images since these commands will fail.  (For instance, https://github.com/broadinstitute/warp/blob/develop/dockers/broad/samtools_picard_bwa/docker_build.sh#L73)

**Comment by zhaohongqiangsoliva** [comment]
Thank you very much, this method is very useful
