### ISSUE TITLE
Optimus pipeline unexpected behaviour for SplitFastq

### ISSUE THREAD

**Issue by opavon** [broadinstitute/warp#850]
Hi all, 

We’ve encountered some strange behaviour from the FastqProcessing (alias SplitFastq) step in the Optimus pipeline (v5.4.3) and I was hoping to get help clarifying what is happening. The [documentation ](https://broadinstitute.github.io/warp/docs/Pipelines/Optimus_Pipeline/README/#optimus-tasks-and-tools) describes this step as being skipped if the files are smaller than 30GB, but that does not seem to be the case. When we run it with two fastq files (R2 was 16GB and R1 was 7GB), the step took over 5h hours to complete and its outputs were two smaller fastq files (13GB and 5GB). Inspection of the fastq.gz files (images below) shows the step is actually doing some modifications to the files - is this expected behaviour? What is the fastqprocess.cpp step actually doing and why isn’t it skipped as the documentation suggests?

Thanks!

Oriol

![Screenshot 2022-10-27 at 11 06 03](https://user-images.githubusercontent.com/38165153/198550333-d0973335-8ecf-4a3e-adaf-7d4d441a6a2b.png)

![Screenshot 2022-10-27 at 11 11 04](https://user-images.githubusercontent.com/38165153/198550367-0f16f430-a708-4d44-b57f-4994c77a741f.png)

![Screenshot 2022-10-27 at 11 10 47](https://user-images.githubusercontent.com/38165153/198550349-ef0da8b5-e352-4e6a-8493-4f4464ffd089.png)

**Comment by khajoue2** [comment]
Hi Oriel, 
The version of Optimus you are using does not skip the splitting step. We are going to release a new version in this PR:https://github.com/broadinstitute/warp/pull/664 that will skip the step. This step investigates each read1 and writes all reads associated with the same cell barcode in the same file split. In addition, it also pre-filters all the cellbarcodes and removes the reads that are more than 1-hamming distance from the whitelist. We needed to split for larger input sizes since STAR cannot run in a single VM if the inputs are more than 100 GB.

**Comment by opavon** [comment]
Thank you for the clarification. Is there a planned release date for this new version? And would it be possible to update the current documentation ([link](https://broadinstitute.github.io/warp/docs/Pipelines/Optimus_Pipeline/README/#optimus-tasks-and-tools)) accordingly? This step also seems to be trimming read1 to the expected length for a given chemistry (e.g. down to 26bp for 10x_v2 with UMI length of 10 and CB length of 16), would be great to add this to the docs too. 

Thanks again!

Oriol

![image](https://user-images.githubusercontent.com/38165153/199699484-5893eecb-96ec-423c-8ee3-347dc8db7b3b.png)


![image](https://user-images.githubusercontent.com/38165153/199699418-0b7f863f-6387-482d-96c8-805b75926c7f.png)

![image](https://user-images.githubusercontent.com/38165153/199699851-09633fd0-cf26-4884-97e7-9cb6202bfe73.png)

![image](https://user-images.githubusercontent.com/38165153/199699884-65a8fee7-5b32-4909-8d92-0f7f6818912a.png)

**Comment by nikellepetrillo** [comment]
Hi Oriol, 
We do not have planned release date for this fix yet. We have an [open PR](https://github.com/broadinstitute/warp/pull/664) that we are actively working on. Once we merge to dev there will be a pre-release tag that you can use. 

The fastq outputs after splitting only retain cell barcodes and UMIs extracted from each read in the intermediate files that get passed to the STAR aligner. We also filter reads that are 2 or more hamming distance from the whitelist. We don't correct for the errors in the cell barcode and UMIs in the splitting step as STAR handles this downstream. We don't typically update our documentation for intermediate files because they don't affect the outputs. These changes will be documented in our release notes. 

In the read 1 output of SplitFastq, we concatenate extracted cell barcodes and the UMIs for each read. The length of the sequence will be the length of the UMI + the length of the cell barcode. This will affect the distribution of base pairs. 

Thanks,
Nikelle

**Comment by ekiernan** [comment]
Hi Oriol,

Yes, we will update the documentation to reflect the correct version. Sorry about the confusion.

**Comment by opavon** [comment]
Great, thank you all for your help and clarifications!
